services:
  reverse-proxy:
    image: "reverse-proxy"
    container_name: "reverse-proxy"
    restart: "always"
    networks: 
      - "social-network-ecosystem"
    ports:
      - "5005:5005"
    depends_on:
      - keycloak
      - psn-user-plugin
      - psn-blog-plugin
      - psn-node-manager
  keycloak:
    image: local-keycloak
    ports:
      - "9080:8080"
    depends_on:
      - db
    networks:
      - social-network-ecosystem
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB: resume
    volumes:
      - ../keycloak-interaction/keycloak/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - social-network-ecosystem
  psn-node-manager:
    image: psn-node-manager
    ports:
      - "8080:8080"
    networks:
      - social-network-ecosystem
    depends_on:
      - keycloak
  psn-user-plugin:
    image: psn-user-plugin
    ports:
      - "8081:8080"
    networks:
      - social-network-ecosystem
    depends_on:
      - psn-node-manager
  psn-blog-plugin:
    image: psn-blog-plugin
    ports:
      - "8082:8080"
    networks:
      - social-network-ecosystem
    depends_on:
      - psn-node-manager
  
  
networks:
  social-network-ecosystem:
    driver: bridge
    name: social-network-ecosystem
    external: false
