events {}

http {
	server {
		listen 5005;
		listen [::]:5005;
		server_name _;
		
		location /auth/realms {
			proxy_pass 				http://psn-keycloak.flycast:80/auth/realms;
			proxy_set_header X-Real-IP 		$remote_addr;
        		proxy_set_header X-Forwarded-For 	$proxy_add_x_forwarded_for;
        		proxy_set_header X-Forwarded-Proto 	$scheme;
        		proxy_set_header X-Forwarded-Host 	psn-reverse-proxy.fly.dev;
			proxy_set_header X-Forwarded-Port 	8080;
                    	add_header Set-Cookie 			$http_cookie;
		}
		
		location /auth/resources {
			proxy_pass 				http://psn-keycloak.flycast:80/auth/resources;
			proxy_set_header X-Real-IP 		$remote_addr;
        		proxy_set_header X-Forwarded-For 	$proxy_add_x_forwarded_for;
        		proxy_set_header X-Forwarded-Proto 	$scheme;
        		proxy_set_header X-Forwarded-Host 	psn-reverse-proxy.fly.dev;
			proxy_set_header X-Forwarded-Port 	8080;
                    	add_header Set-Cookie 			$http_cookie;
		}

		location /blog {
			proxy_pass http://blog-plugin.flycast:80/blog;
		}

		location /user {
			proxy_pass http://keycloak-user-plugin.flycast:80/user;
		}
	}
}
